### ISSUE TITLE
avn compatibility with current Node.js versions

### ISSUE THREAD

**Issue by MikeMcC399** [shadowspawn/node-version-usage#11]
[avn](https://github.com/wbyoung/avn) is listed in the [Compatibility Testing](https://github.com/shadowspawn/node-version-usage#compatibility-testing) table as being compatible with Node.js `14`, however there are multiple reports listed in [avn issues](https://github.com/wbyoung/avn) of problems with Node.js > `10`.  The [avn](https://github.com/wbyoung/avn) site has not been updated for over three years.

Should [avn](https://github.com/wbyoung/avn) still be listed?

Node.js `14` enters [end-of-life](https://github.com/nodejs/release#release-schedule) status on April 30, 2023, so the compatibility table using Node.js `14.15.0` as reference version becomes of limited use if it does not cover currently supported Node.js versions.

**Comment by shadowspawn** [comment]
Actually I only used 14.5.0 as an example three part numeric version rather than a reference version. In fact the testing fixtures are all using versions of 10.x!

I know a few of the node version managers are not currently being developed and multiple are fairly inactive. I could do a revisit and downgrade the ones which are not working with modern Node.js versions.

**Comment by MikeMcC399** [comment]
@shadowspawn 

> Actually I only used 14.5.0 as an example three part numeric version rather than a reference version.

I had a feeling that might be the case!

> I know a few of the node version managers are not currently being developed and multiple are fairly inactive. I could do a revisit and downgrade the ones which are not working with modern Node.js versions.

If you are able to revisit that would make the list much more useful. From my perspective, I would expect that at least Node.js LTS would be supported, better still though would be all of the versions currently listed in the Node.js [Release schedule](https://github.com/nodejs/release#release-schedule) table, also with Node.js 20 just around the corner.

BTW: Thanks for your related comment in the Cypress issues list 🙂 !

**Comment by shadowspawn** [comment]
A small update. I started looking into `avn`. The issue I reproduced is that `avn setup` fails on on node >10. Once installed (using an old node version) avn does allow changing to new node versions when changing directories. The project is not currently being maintained.

- https://github.com/wbyoung/avn/issues/109
- https://github.com/wbyoung/avn/issues/77

Update: project was archived 2023-12-07

**Comment by shadowspawn** [comment]
All of the node version managers other than avn have had commits within the last year.

**Comment by shadowspawn** [comment]
I am playing about with what to do with avn. I am reluctant to simply delete it, but that is a fallback! How about a notes column in the compatibility table?

https://github.com/shadowspawn/node-version-usage/tree/feature/deprecate-avn#compatibility-testing

**Comment by MikeMcC399** [comment]
@shadowspawn 

A notes column would do the trick. Good suggestion!

Maybe also a comment at the bottom of the table [Compatibility testing](https://github.com/shadowspawn/node-version-usage/tree/feature/deprecate-avn#compatibility-testing) to explain the meanings of the column headings? I misread the meaning of the table and thought it meant that the tools ran on the version `14.5.0`, whereas you are only stating that it understands the format `xx.yy.zz`, etc.

**Comment by shadowspawn** [comment]
Hmm, I wasn't entirely happy with the numbers at the top, and your confusion was understandable.

I moved the example versions out of the title row, dropped to 10 so does not look like LTS related, and put in code block so looks a bit more example-ish. Is it more self-evident now, or do you feel still in need of an explanation?

| Utility                                              | simple             | leading `v`        | partial            | Unix EOL           | No EOL             | Win EOL | Notes   |
| :---                                                 | :---:              | :---:              | :---:              | :---:              | :---:              | :---:   |  :---:  |
|                                                      | `10.1.2`           |  `v10.1.2`         | `10.2`             |                    |                    |         |         |
| [asdf](https://github.com/asdf-vm/asdf-nodejs)       | :white_check_mark: | :white_check_mark: | :x:                | :white_check_mark: | :white_check_mark: | :x: | |

**Comment by MikeMcC399** [comment]
I think you need to say somewhere that these are example Node.js version formats only. Maybe write "e.g." in front of each version, add something into the Notes column or write a text comment immediately after the table ends?

Your suggestion so far is in any case an improvement on the previous presentation! 👍🏻

**Comment by shadowspawn** [comment]
> Maybe write "e.g." in front of each version, add something into the Notes column

For amusement, I had already tried both of those but didn't like the appearance or resulting increased table width.

> or write a text comment immediately after the table ends?

I'll stop deluding myself that does not need it, and do that. 😆

**Comment by shadowspawn** [comment]
Thanks for feedback and suggestions @MikeMcC399

**Comment by shadowspawn** [comment]
avn repo now archived:

> This repository has been archived by the owner on Dec 7, 2023. It is now read-only.
