### ISSUE TITLE
windows support column?

### ISSUE THREAD

**Issue by jdx** [shadowspawn/node-version-usage#14]
I feel like it's a little strange we have the "Win EOL" column when a lot (maybe most) of these tools don't actually work on windows. Should we have an extra column for non-wsl Windows support? It looks like we have the data already in the text

**Comment by shadowspawn** [comment]
The Compatibility Testing table is the research data behind the Suggested Compatible Format section. It is to help decide what to put in the `.node-version` file and work with a wider group of people. Or for a particular format, see what products will support it.

Say I work on a Mac using node version manager X which does not work on Windows. But I work with people on Windows, using node version manager Y. What file formats will work for everyone in my team?
