### ISSUE TITLE
Document the `20.x` format?

### ISSUE THREAD

**Issue by spenserblack** [shadowspawn/node-version-usage#20]
This repo is a lifesaver for ensuring compatibility among tools!

Would it be possible to document the format `20.x` and `20.9.x`? Note that `x` is *not* a generic placeholder here, but the actual text in the `.node-version` file. I suppose it could be considered an alternative partial format.

The usage is a bit popular. A search on GitHub of `.node-version` files containing the text `x` yields over 300 results.

https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29%5C.node-version%24%2F+x&ref=opensearch&type=code

**Comment by shadowspawn** [comment]
Thanks. 😄 

I am familiar with `20.x` style from semver specification, but have not seen it mentioned much with node version managers. I checked a few and found `fnm` supports this style, but not supported by `n` or `mise` or `vfox`. I don't think it is widely supported enough to document.

**Comment by spenserblack** [comment]
> I am familiar with `20.x` style from semver specification, but have not seen it mentioned much with node version managers.

Yeah, my first exposure to that format was actions/setup-node, where their basic example (using a `node-version` input, not a `.node-version` file) uses that format. Not that it's important, but I wanted to match the style used in my GH workflow with the contents of my `.node-version` file, which got me curious/concerned about compatibility with tooling.

**Comment by shadowspawn** [comment]
`actions/setup-node` supports partial version numbers, and so does `semver`, so you could perhaps omit the `.x` in their setup to get matching style in the other direction:
- https://github.com/actions/setup-node#supported-version-syntax
- https://github.com/npm/node-semver#x-ranges-12x-1x-12-

**Comment by shadowspawn** [comment]
I forget about trying to survey usage using GitHub searches. Thanks for link. I noticed some false positives due to `x` in path. Restricting search for `x` to just content drops the count to 55:

https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29%5C.node-version%24%2F+content%3Ax&ref=opensearch&type=code

**Comment by spenserblack** [comment]
Oh, wow, I didn't realize so many of the search results were false positives (nor was I aware of the `content:` filter). Thanks for the info! I guess setup-node's `.x` style is pretty non-standard, and not worth documenting then.
