### ISSUE TITLE
Consider creating test suite for the spec

### ISSUE THREAD

**Issue by mrmckeb** [shadowspawn/node-version-usage#9]
Hey, I came across your analysis via https://github.com/nvm-sh/nvm/issues/794 - great work!

I think the next steps are to create a test suite, and have a few people (I'm happy to volunteer) contribute/raise issues against different managers. That project could possibly be spun out into a different org too.

What do you think? Is that something you'd be interested in pursuing?

**Comment by shadowspawn** [comment]
What are you aiming to achieve?

---

I do have the files I use for manual testing in this repo, very simple test suite. 😄 
https://github.com/shadowspawn/node-version-usage/tree/master/fixtures

Much as I like the idea of filling out the few gaps in the partially supported features, there is currently consistent support for single line with unix line ending and three part numeric version. Some of the implementations are 10 years old, so not a lot of incentive for them to change without demand from their users. I think new implementations are likely to be interested in filling out their coverage.

I have made a couple of contributions along the lines you might have in mind:
- https://github.com/direnv/direnv/pull/833
- https://github.com/tkareine/chnode/issues/5

**Comment by shadowspawn** [comment]
Somewhat related. asdf-node does not intend to support partial versions, by design: https://github.com/asdf-vm/asdf-nodejs/issues/235#issuecomment-885809776

**Comment by mrmckeb** [comment]
Apologies for the slow reply, I missed the notification.

What I was hoping to achieve is a standard that version managers can adhere to, as right now it's a little chaotic. 

The solution for us (internally) will be to enforce a common tool, but in the wild (open source) that's much harder.

**Comment by shadowspawn** [comment]
This issue hasn't triggered any other feedback or support in a couple of months.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
